const data = {
  products: [
    {
      name: 'Toofan fan',
      slug: 'toofan-fans',
      category: 'Fans',
      image: '/images/p1.jpg',
      price: 1200,
      countInStock: 50,
      brand: 'Toofan',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality ceiling fans',
    },
    {
      name: 'SEC fan',
      slug: 'sec-fans',
      category: 'Fans',
      image: '/images/p2.jpg',
      price: 1300,
      countInStock: 20,
      brand: 'SEC',
      rating: 4.6,
      numReviews: 10,
      description: 'high quality ceiling fans',
    },
    {
      name: 'Sumeet Mixer grinder',
      slug: 'sumeet-mg',
      category: 'Mixer Grinder',
      image: '/images/p3.jpg',
      price: 4800,
      countInStock: 6,
      brand: 'Sumeet',
      rating: 4.5,
      numReviews: 5,
      description: 'high quality mixer grinder',
    },
    {
      name: 'Bajaj Mixer grinder',
      slug: 'bajaj-mg',
      category: 'Mixer Grinder',
      image: '/images/p4.jpg',
      price: 4800,
      countInStock: 6,
      brand: 'Bajaj',
      rating: 4.7,
      numReviews: 5,
      description: 'high quality mixer grinder',
    },
  ],
};
export default data;
